services:
  vkapi:
    build: ./vkapi
    ports:
      - "127.0.0.1:8082:8082"


  myapp_db:
    image: percona
    environment:
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - ./myapp_db/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    command: --bind-address=0.0.0.0 --port=8081
    ports:
      - "127.0.0.1:8081:8081"

  myapp:
    image: myapp
    volumes:
      - ./myapp/config:/tmp/config:ro
      - ./myapp/wait_for_db:/wait_for_db:ro
    command: /wait_for_db/wait.sh /app/myapp --config=/tmp/config
      # я решил использовать последнюю версию compose file, поэтому в силу отсутствия healthcheck пришлось реализовать ожидание БД у myapp (см. /myapp/wait_for_db/)
    depends_on:
      - vkapi
      - myapp_db
    ports:
      - "127.0.0.1:8083:8083"


networks:
  default:
    name: myapp